### ISSUE TITLE
Configuring custom profiler trigger value seems to only return XDEBUG_ECLIPSE as the value

### ISSUE THREAD

**Issue by mmccollum** [mac-cain13/xdebug-helper-for-chrome#69] opened 2016-07-12 15:31 UTC
I have the following configuration in php.ini:
xdebug.profiler_enable_trigger=1
xdebug.profiler_enable_trigger_value="XDEBUG_PROFILE"
xdebug.profiler_output_dir=/www/xdebug

When I try to configure the plugin to set XDEBUG_PROFILE as the value of the XDEBUG_PROFILE cookie, it  generates the cookie with XDEBUG_ECLIPSE.

This is also true if I enter another string into the value, such as 'TEST'

When I comment out the profiler_enable_trigger_value, xdebug does trigger the profiler.

**Comment by neochief** [comment] 2016-08-04 07:44
For me it looks as if trigger values in plugin are hardcoded to XDEBUG_ECLIPSE. I can't change them, nothing is being saved and the cookie is set to XDEBUG_ECLIPSE for both trace and profiler.

**Comment by neochief** [comment] 2016-08-04 08:52
Okay, the issue is fixed in this PR: https://github.com/mac-cain13/xdebug-helper-for-chrome/pull/70

**Comment by tdtm** [comment] 2016-08-30 11:35
The issue seems to remain in the Chrome store version (and its last update was on March 28, 2016, so that would make sense).

I'll load the dev version on my end, but it'd be great to have the person with appropriate Store access to do it up there as well.

**Comment by mac-cain13** [comment] 2016-08-30 12:06
Thanks for the reminder. This did fall off my radar, I'm sorry. I'll merge #70 and release a new version as soon as I have some time!

**Comment by tdtm** [comment] 2016-08-30 12:44
No worries, it happens! #66 seems good to go as well.

**Comment by mac-cain13** [comment] 2016-10-24 16:44
This is (finally) merged!

**Closed by mac-cain13** 2016-10-24 16:44 UTC

**Comment by eselskas** [comment] 2019-10-11 10:18
This is still happening :(
