### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by MUTOgen** [mac-cain13/xdebug-helper-for-chrome#48] opened 2015-07-14 08:24 UTC
Hi!
I found that plugin doesn'to work with Chrome 45.0.2453.0 dev-m (64-bit)

**Comment by mac-cain13** [comment] 2015-07-14 08:27
Hi! 

That's too bad. :( Can you describe what you expected to happen and what happend instead? Did it work on previous versions on Chrome for you?

**Comment by MUTOgen** [comment] 2015-07-14 08:31
Yes, it worked some time ago.
I don't have bug-icon in address line after update. Also i turned on error logging for plugin and see red alert on this line

```
updateIcon(response.status, tabId);
```

**Comment by tabacco** [comment] 2015-07-14 17:20
I can reproduce this as well:
![](http://i.imgur.com/TC5IG6P.png)

**Comment by MUTOgen** [comment] 2015-07-16 07:07
Any solutions?

**Comment by mac-cain13** [comment] 2015-07-16 09:52
Obviously something changed in the new Chrome version. We should debug what is going wrong and fix it. I'll look into it as soon as I'm able to, but I'm quite busy at the moment so can't guarantee anything.

A pull request would be very much appreciated, so please feel free to dive into this and send a PR with a fix if you can.

**Comment by mac-cain13** [comment] 2015-07-16 15:33
Ok just looked quickly, am I correct all of you are on the Dev channel? My Stable Chrome is still version 43, so it seems this only occurs on the Dev version right? Everything on my Stable version seems fine.

**Comment by MUTOgen** [comment] 2015-07-16 15:34
I would like to switch channel to stable and rollback, but i have no idea why i'm on dev :)

**Comment by tabacco** [comment] 2015-07-16 15:34
Yeah, this is on the dev channel, but dev channel builds do become stable channel builds eventually :)

**Comment by mac-cain13** [comment] 2015-07-17 06:36
Correct, but they also get fixes before getting to stable. ;) So have to look into if it's a Chrome issue or a issue of the plugin. Chrome shouldn't break plugins without warning of a backward incompatible change in the docs. I'll check if there is such a change.

**Comment by tabacco** [comment] 2015-07-23 16:45
Seems to be working as of 45.0.2454.12

**Comment by mac-cain13** [comment] 2015-07-24 05:51
Cool, seems to be an Chrome Dev Channel bug then. Thanks for reporting the fix! Will close this issue.

**Closed by mac-cain13** 2015-07-24 05:51 UTC
