### ISSUE TITLE
Xdebug helper doesn't appear w/ chrome

### ISSUE THREAD

**Issue by shukyp** [mac-cain13/xdebug-helper-for-chrome#40] opened 2014-01-06 15:57 UTC
many times the "bug" image doesn't appear next to the end of the URL line

what does it mean ?
how to be resolved ?

tnx

**Comment by allejo** [comment] 2015-01-17 04:10
If this is a bug with Chrome, maybe instead of adding it in the URL bar, just add it as an icon next to it like a lot of other extensions do? Or at least allow for the option to do so? Opening a new tab of Chrome to get the icon back is bothersome.

**Comment by mac-cain13** [comment] 2015-01-18 13:43
Just did some small changes and pushed version 1.4.3 out. I'm wondering if the domain filter is the problem, maybe sometimes the extension can't find a domain and will not show up because of that. I've not changed this check to show the icon if we can't find a domain.

That said, I don't have a good reproduction path and I'm not using the extension enough to debug this strange behavior. I think it would be an "okay" solution to move to a button, if that bothers you outside work you could use a profile to switch between a PHP dev and a normal use profile.

I currently don't have the time to test and implement this extension as a "normal" button, but I'm happy to take a Pull Request doing this. So let me know if any of you start working on it!

**Comment by mcdado** [comment] 2015-01-26 21:28
+1 on moving to a button! ;)

**Comment by revolutionate** [comment] 2015-04-23 12:34
This hasn't happened to me in quite a while - it used to be extremely frequent. Are other people still seeing it? Did it get fixed in Chrome perhaps?

**Comment by ElijahLynn** [comment] 2015-04-23 17:33
Haven't seen in it a while either.

**Comment by mac-cain13** [comment] 2015-05-14 10:16
Good to hear it's working correctly again! Probably a Chrome fix indeed. I'll close the issue and will assume Chrome fixed it now!

**Closed by mac-cain13** 2015-05-14 10:16 UTC
